{
   "services": {
      "envoy": {
         "environment": [
            "loglevel=debug"
         ],
         "image": "envoyproxy/envoy-alpine:latest",
         "ports": [
            "10000:10000",
            "9999:9999"
         ],
         "volumes": [
            "./envoy.yaml:/etc/envoy/envoy.yaml"
         ]
      },
      "grafana": {
         "image": "grafana/grafana",
         "ports": [
            "3000:3000"
         ]
      },
      "prometheus": {
         "image": "quay.io/prometheus/prometheus",
         "ports": [
            "9090:9090"
         ],
         "volumes": [
            "./prometheus.yml:/etc/prometheus/prometheus.yml"
         ]
      }
   },
   "version": "3"
}
